package com.xroig.finance.service;

import com.xroig.finance.dto.BudgetDtos.AnnualBudget;
import com.xroig.finance.dto.BudgetDtos.AnnualRow;
import com.xroig.finance.dto.BudgetDtos.MonthCell;
import com.xroig.finance.model.Budget;
import com.xroig.finance.model.Category;
import com.xroig.finance.model.RecurringBudget;
import com.xroig.finance.shared.domain.TransactionType;
import com.xroig.finance.repository.BudgetRepository;
import com.xroig.finance.repository.CategoryRepository;
import com.xroig.finance.repository.RecurringBudgetRepository;
import com.xroig.finance.repository.TransactionRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Service
@Transactional(readOnly = true)
public class BudgetService {

    private final BudgetRepository budgetRepository;
    private final CategoryRepository categoryRepository;
    private final TransactionRepository transactionRepository;
    private final RecurringBudgetRepository recurringBudgetRepository;

    public BudgetService(BudgetRepository budgetRepository,
                         CategoryRepository categoryRepository,
                         TransactionRepository transactionRepository,
                         RecurringBudgetRepository recurringBudgetRepository) {
        this.budgetRepository = budgetRepository;
        this.categoryRepository = categoryRepository;
        this.transactionRepository = transactionRepository;
        this.recurringBudgetRepository = recurringBudgetRepository;
    }

    /**
     * Annual budget matrix mirroring the user's spreadsheet: every category
     * applicable to the account, with its planned amount and real movement for
     * each of the 12 months. Budgets live on leaf categories: a top-level
     * category without subcategories (or a subcategory) is editable; a category
     * with subcategories is shown as the aggregate of its children and is not
     * budgeted directly, with its children nested as editable rows. When
     * {@code accountId} is null the figures are the aggregate of all accounts
     * and cells carry no {@code budgetId} (read-only).
     *
     * <p>The planned amount of a leaf cell is the manual {@link Budget} when one
     * exists (the inline-edited override), otherwise the value generated by the
     * category's recurrence (see {@link RecurringBudget}); recurrences only feed
     * the planned side, never the real one.
     */
    public AnnualBudget annual(int year, Long accountId) {
        List<Category> categories = accountId != null
                ? categoryRepository.findVisibleForAccount(accountId)
                : categoryRepository.findAll();

        List<Budget> budgets = accountId != null
                ? budgetRepository.findByAccountIdAndYear(accountId, year)
                : budgetRepository.findByYear(year);

        // Manual planned amount, whether a manual budget exists (override flag),
        // and — per account — the budget id, all keyed by category per month.
        Map<Long, BigDecimal[]> manualByCat = new HashMap<>();
        Map<Long, boolean[]> hasManualByCat = new HashMap<>();
        Map<Long, Long[]> budgetIdByCat = new HashMap<>();
        for (Budget b : budgets) {
            Long catId = b.getCategory().getId();
            int idx = b.getMonth() - 1;
            manualByCat.computeIfAbsent(catId, k -> zero12())[idx] =
                    manualByCat.get(catId)[idx].add(b.getAmount());
            hasManualByCat.computeIfAbsent(catId, k -> new boolean[12])[idx] = true;
            if (accountId != null) {
                budgetIdByCat.computeIfAbsent(catId, k -> new Long[12])[idx] = b.getId();
            }
        }

        // Recurrence-generated planned amount per category per month.
        Map<Long, BigDecimal[]> recurrenceByCat = new HashMap<>();
        List<RecurringBudget> recurrences = accountId != null
                ? recurringBudgetRepository.findActiveByAccountWithAmounts(accountId)
                : recurringBudgetRepository.findAllActiveWithAmounts();
        for (RecurringBudget r : recurrences) {
            BigDecimal[] arr = recurrenceByCat.computeIfAbsent(r.getCategory().getId(), k -> zero12());
            for (int m = 1; m <= 12; m++) {
                if (r.appliesToMonth(m)) {
                    BigDecimal amount = r.amountAt(LocalDate.of(year, m, 1));
                    if (amount != null) {
                        arr[m - 1] = amount;
                    }
                }
            }
        }

        // Merge: a manual budget overrides the recurrence; otherwise the
        // recurrence fills the cell; otherwise zero.
        Map<Long, BigDecimal[]> plannedByCat = new HashMap<>();
        for (Category c : categories) {
            Long id = c.getId();
            BigDecimal[] manual = manualByCat.get(id);
            boolean[] hasManual = hasManualByCat.get(id);
            BigDecimal[] recurrence = recurrenceByCat.get(id);
            BigDecimal[] planned = zero12();
            for (int m = 0; m < 12; m++) {
                if (hasManual != null && hasManual[m]) {
                    planned[m] = manual[m];
                } else if (recurrence != null) {
                    planned[m] = recurrence[m];
                }
            }
            plannedByCat.put(id, planned);
        }

        // Real movement per exact category (no roll-up) per month; parents are
        // aggregated from their children below.
        Map<Long, BigDecimal[]> actualByCat = new HashMap<>();
        for (Object[] row : transactionRepository.sumByExactCategoryAndMonthOfYear(year, accountId)) {
            Long catId = ((Number) row[0]).longValue();
            int idx = ((Number) row[1]).intValue() - 1;
            actualByCat.computeIfAbsent(catId, k -> zero12())[idx] = (BigDecimal) row[2];
        }

        Map<Long, List<Category>> childrenByParent = new HashMap<>();
        for (Category c : categories) {
            if (c.getParent() != null) {
                childrenByParent.computeIfAbsent(c.getParent().getId(), k -> new ArrayList<>()).add(c);
            }
        }

        List<AnnualRow> income = new ArrayList<>();
        List<AnnualRow> expense = new ArrayList<>();
        for (Category c : categories) {
            // Subcategories are emitted nested under their parent, not at top level.
            if (c.getParent() != null) {
                continue;
            }
            List<Category> children = childrenByParent.getOrDefault(c.getId(), List.of());
            AnnualRow row = children.isEmpty()
                    ? leafRow(c, plannedByCat, budgetIdByCat, actualByCat)
                    : parentRow(c, children, plannedByCat, budgetIdByCat, actualByCat);
            (c.getType() == TransactionType.INCOME ? income : expense).add(row);
        }

        income.sort(Comparator.comparing(AnnualRow::category, String.CASE_INSENSITIVE_ORDER));
        expense.sort(Comparator.comparing(AnnualRow::category, String.CASE_INSENSITIVE_ORDER));
        return new AnnualBudget(year, accountId, income, expense);
    }

    /** Editable row for a leaf category (its own planned and real amounts). */
    private AnnualRow leafRow(Category c,
                              Map<Long, BigDecimal[]> plannedByCat,
                              Map<Long, Long[]> budgetIdByCat,
                              Map<Long, BigDecimal[]> actualByCat) {
        BigDecimal[] planned = plannedByCat.getOrDefault(c.getId(), zero12());
        BigDecimal[] actual = actualByCat.getOrDefault(c.getId(), zero12());
        Long[] ids = budgetIdByCat.get(c.getId());
        List<MonthCell> cells = new ArrayList<>(12);
        for (int m = 0; m < 12; m++) {
            cells.add(new MonthCell(ids != null ? ids[m] : null, planned[m], actual[m]));
        }
        return new AnnualRow(c.getId(), c.getName(), c.getColor(), c.getType(), true, cells, List.of());
    }

    /**
     * Read-only aggregate row for a parent category: planned and real are the
     * sum over the parent's own amounts (legacy direct budgets/movements) and
     * those of its children, which are emitted as nested editable rows.
     */
    private AnnualRow parentRow(Category c, List<Category> children,
                                Map<Long, BigDecimal[]> plannedByCat,
                                Map<Long, Long[]> budgetIdByCat,
                                Map<Long, BigDecimal[]> actualByCat) {
        BigDecimal[] aggBudget = zero12();
        BigDecimal[] aggActual = zero12();
        addInto(aggBudget, plannedByCat.get(c.getId()));
        addInto(aggActual, actualByCat.get(c.getId()));

        List<AnnualRow> childRows = new ArrayList<>();
        for (Category child : children) {
            childRows.add(leafRow(child, plannedByCat, budgetIdByCat, actualByCat));
            addInto(aggBudget, plannedByCat.get(child.getId()));
            addInto(aggActual, actualByCat.get(child.getId()));
        }
        childRows.sort(Comparator.comparing(AnnualRow::category, String.CASE_INSENSITIVE_ORDER));

        List<MonthCell> cells = new ArrayList<>(12);
        for (int m = 0; m < 12; m++) {
            cells.add(new MonthCell(null, aggBudget[m], aggActual[m]));
        }
        return new AnnualRow(c.getId(), c.getName(), c.getColor(), c.getType(), false, cells, childRows);
    }

    private static void addInto(BigDecimal[] target, BigDecimal[] add) {
        if (add == null) {
            return;
        }
        for (int m = 0; m < 12; m++) {
            target[m] = target[m].add(add[m]);
        }
    }

    private static BigDecimal[] zero12() {
        BigDecimal[] arr = new BigDecimal[12];
        java.util.Arrays.fill(arr, BigDecimal.ZERO);
        return arr;
    }
}
