package com.xroig.finance.budgets.infrastructure.persistence;

import com.xroig.finance.accounts.infrastructure.persistence.AccountJpaEntity;
import com.xroig.finance.budgets.application.AnnualBudgetView;
import com.xroig.finance.budgets.application.AnnualBudgetView.AnnualRow;
import com.xroig.finance.budgets.application.AnnualBudgetView.MonthCell;
import com.xroig.finance.budgets.application.BudgetQueryPort;
import com.xroig.finance.budgets.application.BudgetView;
import com.xroig.finance.budgets.application.BudgetView.AccountRef;
import com.xroig.finance.budgets.application.BudgetView.CategoryRef;
import com.xroig.finance.budgets.domain.BudgetId;
import com.xroig.finance.categories.infrastructure.persistence.CategoryJpaEntity;
import com.xroig.finance.categories.infrastructure.persistence.CategoryJpaRepository;
import com.xroig.finance.model.RecurringBudget;
import com.xroig.finance.repository.RecurringBudgetRepository;
import com.xroig.finance.repository.TransactionRepository;
import com.xroig.finance.shared.domain.TransactionType;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Read-side adapter (CQRS) for the budgets context: assembles {@link BudgetView} read
 * models and the annual {@link AnnualBudgetView} matrix from the persistence graph,
 * without reconstructing aggregates to read.
 *
 * <p>The matrix mirrors the user's spreadsheet. Budgets live on leaf categories: a
 * top-level category without subcategories (or a subcategory) is editable; a category
 * with subcategories is shown as the read-only aggregate of its children, with its
 * children nested as editable rows. The planned amount of a leaf cell is the manual
 * {@code Budget} when one exists (the inline-edited override), otherwise the value
 * generated by the category's recurrence (which only feeds the planned side), otherwise
 * zero. When {@code accountId} is null the figures are the aggregate of all accounts and
 * cells carry no {@code budgetId} (read-only).
 *
 * <p>While the recurrence command side is still legacy, this read uses the legacy
 * {@code RecurringBudgetRepository}/{@code TransactionRepository} for the recurrence and
 * real-movement sums; it will point at the budgets context's own stores as they migrate.
 */
@Component
public class BudgetQueryAdapter implements BudgetQueryPort {

    private final BudgetJpaRepository budgets;
    private final CategoryJpaRepository categories;
    private final RecurringBudgetRepository recurrences;
    private final TransactionRepository transactions;

    public BudgetQueryAdapter(BudgetJpaRepository budgets, CategoryJpaRepository categories,
                              RecurringBudgetRepository recurrences, TransactionRepository transactions) {
        this.budgets = budgets;
        this.categories = categories;
        this.recurrences = recurrences;
        this.transactions = transactions;
    }

    @Override
    public List<BudgetView> find(int year, int month, Long accountId) {
        List<BudgetJpaEntity> rows = accountId != null
                ? budgets.findByAccountIdAndYearAndMonth(accountId, year, month)
                : budgets.findByYearAndMonth(year, month);
        return rows.stream().map(BudgetQueryAdapter::toView).toList();
    }

    @Override
    public Optional<BudgetView> findById(BudgetId id) {
        return budgets.findById(id.value()).map(BudgetQueryAdapter::toView);
    }

    @Override
    public AnnualBudgetView annual(int year, Long accountId) {
        List<CategoryJpaEntity> categoryList = accountId != null
                ? categories.findVisibleForAccount(accountId)
                : categories.findAll();

        List<BudgetJpaEntity> budgetList = accountId != null
                ? budgets.findByAccountIdAndYear(accountId, year)
                : budgets.findByYear(year);

        // Manual planned amount, whether a manual budget exists (override flag),
        // and — per account — the budget id, all keyed by category per month.
        Map<Long, BigDecimal[]> manualByCat = new HashMap<>();
        Map<Long, boolean[]> hasManualByCat = new HashMap<>();
        Map<Long, Long[]> budgetIdByCat = new HashMap<>();
        for (BudgetJpaEntity b : budgetList) {
            Long catId = b.getCategory().getId();
            int idx = b.getMonth() - 1;
            manualByCat.computeIfAbsent(catId, k -> zero12())[idx] =
                    manualByCat.get(catId)[idx].add(b.getAmount());
            hasManualByCat.computeIfAbsent(catId, k -> new boolean[12])[idx] = true;
            if (accountId != null) {
                budgetIdByCat.computeIfAbsent(catId, k -> new Long[12])[idx] = b.getId();
            }
        }

        // Recurrence-generated planned amount per category per month.
        Map<Long, BigDecimal[]> recurrenceByCat = new HashMap<>();
        List<RecurringBudget> active = accountId != null
                ? recurrences.findActiveByAccountWithAmounts(accountId)
                : recurrences.findAllActiveWithAmounts();
        for (RecurringBudget r : active) {
            BigDecimal[] arr = recurrenceByCat.computeIfAbsent(r.getCategory().getId(), k -> zero12());
            for (int m = 1; m <= 12; m++) {
                if (r.appliesToMonth(m)) {
                    BigDecimal amount = r.amountAt(LocalDate.of(year, m, 1));
                    if (amount != null) {
                        arr[m - 1] = amount;
                    }
                }
            }
        }

        // Merge: a manual budget overrides the recurrence; otherwise the recurrence
        // fills the cell; otherwise zero.
        Map<Long, BigDecimal[]> plannedByCat = new HashMap<>();
        for (CategoryJpaEntity c : categoryList) {
            Long id = c.getId();
            BigDecimal[] manual = manualByCat.get(id);
            boolean[] hasManual = hasManualByCat.get(id);
            BigDecimal[] recurrence = recurrenceByCat.get(id);
            BigDecimal[] planned = zero12();
            for (int m = 0; m < 12; m++) {
                if (hasManual != null && hasManual[m]) {
                    planned[m] = manual[m];
                } else if (recurrence != null) {
                    planned[m] = recurrence[m];
                }
            }
            plannedByCat.put(id, planned);
        }

        // Real movement per exact category (no roll-up) per month; parents are
        // aggregated from their children below.
        Map<Long, BigDecimal[]> actualByCat = new HashMap<>();
        for (Object[] row : transactions.sumByExactCategoryAndMonthOfYear(year, accountId)) {
            Long catId = ((Number) row[0]).longValue();
            int idx = ((Number) row[1]).intValue() - 1;
            actualByCat.computeIfAbsent(catId, k -> zero12())[idx] = (BigDecimal) row[2];
        }

        Map<Long, List<CategoryJpaEntity>> childrenByParent = new HashMap<>();
        for (CategoryJpaEntity c : categoryList) {
            if (c.getParent() != null) {
                childrenByParent.computeIfAbsent(c.getParent().getId(), k -> new ArrayList<>()).add(c);
            }
        }

        List<AnnualRow> income = new ArrayList<>();
        List<AnnualRow> expense = new ArrayList<>();
        for (CategoryJpaEntity c : categoryList) {
            // Subcategories are emitted nested under their parent, not at top level.
            if (c.getParent() != null) {
                continue;
            }
            List<CategoryJpaEntity> children = childrenByParent.getOrDefault(c.getId(), List.of());
            AnnualRow row = children.isEmpty()
                    ? leafRow(c, plannedByCat, budgetIdByCat, actualByCat)
                    : parentRow(c, children, plannedByCat, budgetIdByCat, actualByCat);
            (c.getType() == TransactionType.INCOME ? income : expense).add(row);
        }

        income.sort(Comparator.comparing(AnnualRow::category, String.CASE_INSENSITIVE_ORDER));
        expense.sort(Comparator.comparing(AnnualRow::category, String.CASE_INSENSITIVE_ORDER));
        return new AnnualBudgetView(year, accountId, income, expense);
    }

    /** Editable row for a leaf category (its own planned and real amounts). */
    private static AnnualRow leafRow(CategoryJpaEntity c,
                                     Map<Long, BigDecimal[]> plannedByCat,
                                     Map<Long, Long[]> budgetIdByCat,
                                     Map<Long, BigDecimal[]> actualByCat) {
        BigDecimal[] planned = plannedByCat.getOrDefault(c.getId(), zero12());
        BigDecimal[] actual = actualByCat.getOrDefault(c.getId(), zero12());
        Long[] ids = budgetIdByCat.get(c.getId());
        List<MonthCell> cells = new ArrayList<>(12);
        for (int m = 0; m < 12; m++) {
            cells.add(new MonthCell(ids != null ? ids[m] : null, planned[m], actual[m]));
        }
        return new AnnualRow(c.getId(), c.getName(), c.getColor(), c.getType(), true, cells, List.of());
    }

    /**
     * Read-only aggregate row for a parent category: planned and real are the sum over
     * the parent's own amounts (legacy direct budgets/movements) and those of its
     * children, which are emitted as nested editable rows.
     */
    private static AnnualRow parentRow(CategoryJpaEntity c, List<CategoryJpaEntity> children,
                                       Map<Long, BigDecimal[]> plannedByCat,
                                       Map<Long, Long[]> budgetIdByCat,
                                       Map<Long, BigDecimal[]> actualByCat) {
        BigDecimal[] aggBudget = zero12();
        BigDecimal[] aggActual = zero12();
        addInto(aggBudget, plannedByCat.get(c.getId()));
        addInto(aggActual, actualByCat.get(c.getId()));

        List<AnnualRow> childRows = new ArrayList<>();
        for (CategoryJpaEntity child : children) {
            childRows.add(leafRow(child, plannedByCat, budgetIdByCat, actualByCat));
            addInto(aggBudget, plannedByCat.get(child.getId()));
            addInto(aggActual, actualByCat.get(child.getId()));
        }
        childRows.sort(Comparator.comparing(AnnualRow::category, String.CASE_INSENSITIVE_ORDER));

        List<MonthCell> cells = new ArrayList<>(12);
        for (int m = 0; m < 12; m++) {
            cells.add(new MonthCell(null, aggBudget[m], aggActual[m]));
        }
        return new AnnualRow(c.getId(), c.getName(), c.getColor(), c.getType(), false, cells, childRows);
    }

    private static void addInto(BigDecimal[] target, BigDecimal[] add) {
        if (add == null) {
            return;
        }
        for (int m = 0; m < 12; m++) {
            target[m] = target[m].add(add[m]);
        }
    }

    private static BigDecimal[] zero12() {
        BigDecimal[] arr = new BigDecimal[12];
        Arrays.fill(arr, BigDecimal.ZERO);
        return arr;
    }

    private static BudgetView toView(BudgetJpaEntity entity) {
        AccountJpaEntity account = entity.getAccount();
        CategoryJpaEntity category = entity.getCategory();
        return new BudgetView(entity.getId(),
                new AccountRef(account.getId(), account.getName(), account.getType(), account.getInitialBalance()),
                new CategoryRef(category.getId(), category.getName(), category.getType(), category.getColor()),
                entity.getYear(), entity.getMonth(), entity.getAmount());
    }
}
