create table accounts (
    id              bigint generated by default as identity primary key,
    name            varchar(255)   not null,
    type            varchar(255)   not null,
    initial_balance numeric(38, 2) not null
);

create table categories (
    id    bigint generated by default as identity primary key,
    name  varchar(255) not null unique,
    type  varchar(255) not null check (type in ('INCOME', 'EXPENSE')),
    color varchar(255) not null
);

create table transactions (
    id          bigint generated by default as identity primary key,
    date        date           not null,
    amount      numeric(38, 2) not null,
    description varchar(255),
    type        varchar(255)   not null check (type in ('INCOME', 'EXPENSE')),
    account_id  bigint         not null references accounts (id),
    category_id bigint         not null references categories (id)
);

create index idx_transactions_date on transactions (date);
create index idx_transactions_account on transactions (account_id);
create index idx_transactions_category on transactions (category_id);

create table transfers (
    id              bigint generated by default as identity primary key,
    date            date           not null,
    amount          numeric(38, 2) not null,
    description     varchar(255),
    from_account_id bigint         not null references accounts (id),
    to_account_id   bigint         not null references accounts (id)
);

create index idx_transfers_from_account on transfers (from_account_id);
create index idx_transfers_to_account on transfers (to_account_id);

create table monthly_budgets (
    id          bigint generated by default as identity primary key,
    category_id bigint         not null references categories (id),
    year        integer        not null,
    month       integer        not null check (month between 1 and 12),
    amount      numeric(38, 2) not null,
    unique (category_id, year, month)
);
