create table category_rules (
    id          bigint generated by default as identity primary key,
    pattern     varchar(255) not null,
    category_id bigint       not null references categories (id)
);
